FROM node:25.1.0-alpine AS builder

WORKDIR /home
COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.29.3-alpine

WORKDIR /home

COPY --from=builder /home/dist ./

COPY --from=builder /home/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]